config/routes.rb
Rails.application.routes.draw do
  resources :patterns
  resources :logs
  resources :users
  resources :parsers
  resources :events
  resources :synonyms
  
  root "sessions#new"

  get "sessions/new"
  get "users/new"

  get "/start" => "analyzer#index"
  get "/analyze" => "analyzer#analyze"
  get "analyzer/group"
  get "/split" => "analyzer#split_element"
  get "/save_text" => "analyzer#save_text"
  get "/replace" => "analyzer#replace_data"
  post "/save_log" => "analyzer#save_log"
  post "/save_log_success" => "analyzer#save_log_success"
  get "/search" => "analyzer#help_search"
  
  get "/event" => "events#index"
  get "/taxonomy" => "events#taxonomy"
  post "/save_synonym" => "events#save_synonym"
  post "/save_event" => "events#save_event"
  post "/save_tag" => "events#save_tag"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/signup" => "users#new"
  post "/users" => "users#create"
  get "/users" => "users#index"

  get "/parsers" => "parsers#index"
  get "/export_parsers" => "parsers#export"
  post "/form" => "parsers#form_save"
  post "/import_parsers" => "parsers#import"
  resources :parsers do
    get :autocomplete_parser_name, :on => :collection
  end

  get "/patterns" => "patterns#index"
  post "/save" => "patterns#create_with_log"
  get "patterns/autocomplete_pattern_text"
  get "/export_patterns" => "patterns#export"
  post "/import_patterns" => "patterns#import"

  get "/export_logs" => "logs#export"
  

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :synonyms, dependent: :destroy

	def self.search(search)
    if search
      where("LOWER(tag) LIKE :search OR LOWER(clasification) LIKE :search", search: "%#{search.downcase}%") 
    else
      []
    end
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  require 'csv'
  require 'pp'

	def index
    pattern = session[:pattern]
    log = session[:log]
    @data = []

    ## parse data from log management
    if session[:log] && session[:pattern]
      grok = Grok.new
      parsers = Parser.all
      parsers.each do |p|
        grok.add_pattern(p.name, p.expression)
      end

      grok.compile(pattern)
      m = grok.match(log)

      check = {}
      pattern.split(' ').each do |part|
        part.gsub!(/[\{\}\%]/, '')

        # check if there are more parts with same name and match them appropriately
        if check.key?(part)
          check[part] += 1
          capture = m.captures[part][check[part]]
        else
          check[part] = 0
          if m
            capture = m.captures[part].first
          else
            capture = '<UNKNOWN>'
          end
        end
        @data << { name: part, text: capture }
      end
    end

    @event_data = find_event(log) 
	end # def index

  def find_event(log)
    events = Event.all
    data = {}
    events.each do |event|
      data[event.clasification] = event.tag if log.include? event.tag
    end
    data
  end # def find_event

  def taxonomy
    @events = Event.all

    # CSV.foreach(File.path(Rails.root.join('public', 'patterns', 'taxonomy.csv'))) do |row|
    #   event_data = row[0].split(';')
    #   event = Event.new(
    #                     :tag => event_data[0],
    #                     :clasification => event_data[1],
    #                     :description => event_data[2],
    #                     :original => true 
    #                    )
    #   event.save
    # end
  end # def taxonomy

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        
        format.html { redirect_to '/events', notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.js
        format.html { redirect_to '/events/new', notice: 'Event is already present in the database.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to '/events', notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      event.require(:event).permit(:tag, :clasification, :description)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'csv'
  require 'pp'
  require 'grok-pure'
  add_flash_types :success, :warn

	def index
    @pattern = session[:pattern]
    @log = session[:log]
    @pattern_source = Pattern.where("text LIKE :search", search: "#{session[:pattern]}%").first 
    if @pattern_source == nil
      @warning = "WARNING: log pattern is not recognized. You won't be able to save event pattern! (To resolve this, process valid log pattern)"
    else
      @source = @pattern_source.source 
    end
    @data = []

    ## parse data from log management
    if session[:log] && session[:pattern]
      grok = Grok.new
      parsers = Parser.all
      parsers.each do |p|
        grok.add_pattern(p.name, p.expression)
      end

      grok.compile(@pattern)
      m = grok.match(@log)

      check = {}

      if @pattern_source.try(:event_pattern)
        event =  @pattern_source.event_pattern.split(' ') 
      else 
        event = []
      end
      @pattern.split(' ').each_with_index do |part, i|
        part.gsub!(/[\{\}\%]/, '')

        if false#check.key?(part)
          check[part] += 1
          capture = m.captures[part][check[part]]
        else
          check[part] = 0
          if m
            capture = m.captures[part].first
          else
            capture = '<UNKNOWN>'
          end
        end
        name = part
        name = event[i] if @pattern_source.try(:event_pattern)
        @data << { name: part, text: capture, event: name }
      end
    end

    if session[:log]
      @event_data = find_event(@log) 
    end
	end # def index

  def find_event(log)
    events = Event.all
    data = {}
    events.each do |event|
      data[event.clasification] = event.tag if log =~ /\b#{event.tag}\b/i
      event.synonyms.each do |synonym|
        data[event.clasification] = event.tag if log =~ /\b#{synonym.text}\b/i
      end
    end
    data
  end # def find_event

  def taxonomy
    if params[:search]
      @events = Event.search(params[:search]) 
    else
      @events = Event.all
    end
  end # def taxonomy

  def save_synonym
    @event = Event.new
    synonym = Synonym.new(text: params[:text], event_id: params[:id])

    respond_to do |format|
      if synonym.save
        format.html { redirect_to '/taxonomy', notice: 'Synonym was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.js
        format.html { redirect_to '/events/new', notice: 'Synonym is already present in the database.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def save_event
    pattern = Pattern.where("text LIKE :search", search: "#{session[:pattern]}%").first
    pattern.update_attributes(event_pattern: params[:event_pattern])

    data = {:message => "Success"}
    render :json => data, :status => :ok
  end

  def save_tag
    pattern = Pattern.where("text LIKE :search", search: "#{session[:pattern]}%").first

    tag = Tag.new(text: params[pattern.text][:tag], pattern_id: pattern.id)
    respond_to do |format|
      if tag.save
        format.html { redirect_to '/event', notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.js
        format.html { redirect_to '/event', notice: 'Tag is already present in the database.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        
        format.html { redirect_to '/events', notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.js
        format.html { redirect_to '/events/new', notice: 'Event is already present in the database.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to '/events', notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      event.require(:event).permit(:tag, :clasification, :description)
    end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_form.html.erb
<%= form_tag '/save_synonym', method: :post do %>
	<div class="form-group">
		<%= label_tag :tag, "Tag:" %>
		<% event_data = Event.find(params[:id]) %>
    <%= text_field_tag :tag, event_data.tag, class: "form-control", disabled: true %>
    <%= label_tag :text, "Synonym:" %>
	  <%= text_field_tag :text, '', class: "form-control" %>
	  <%= text_field_tag :id, params[:id], class: 'hide' %>
    <%= submit_tag "Submit", class: "btn btn-default btn-lg", id: "pattern-create" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div id="new-synonym">
	<h1>Adding Synonym</h1>

	<%= render 'form' %>

	<%= button_to '/taxonomy', class: "btn btn-default btn-lg edit-pattern", :method => :get do %>
	  Back
	<% end %>

	<h1>Deleting Synonym</h1>

	<% @event = Event.find(params[:id]) %>	
      <table class="table table-striped">
			  <thead>
			    <tr>
			      <th></th>
			      <th></th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @event.synonyms.each do |synonym| %>
			      <tr>
			        <td style="vertical-align: middle;"><%= synonym.text %></td>
			        <td>
			        	<%= button_to synonym, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
        					Delete
      					<% end %>
      				</td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>

</div>

app/views/events/index.html.erb
<div id="warn" style="color:#e36812;"><%= @warning %></div>
<div id="notification" style="color:green;"></div>

<div id="parts">

<% unless @data.size == 0 %>
	<div id="original">
	  <table class="table table-striped">
	    <thead>
	      <tr>
	        <th>Text</th>
	        <th>Log data</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @data.each do |d| %>
	        <tr>
	          <td id="pat-text"><%= d[:text] %></td>
	          <td id="pat-source"><%= d[:name] %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>
	<div class="log-pattern hide"><%= @pattern %></div>

	<div id="new">
	  <table class="table table-striped">
	    <thead>
	      <tr>
	        <th>Event data</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @data.each do |d| %>
	        <tr>
	          <td id="pat-source"><%= text_field_tag :log, d[:event], class: "form-control" %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>

	<div id="event-options">
    

    <%= form_for @pattern, url: '/save_tag' do |f| %>
    	<div id="search-input">
        <%= f.text_field :tag, placeholder: 'tag', class: "form-control left", id: "output-tag" %>
      </div>
        <%= f.submit "Add tag", class: "btn btn-primary btn-lg left", id: "add-tag" %>
    <% end %>

    <input type="button" onclick="event_pattern()" class="btn btn-primary btn-lg save-event" value="Save event data to log pattern"/>

  </div>

	<div id="divider" style="clear:both;"></div>

	

	<div id="events">
		<h3> Events: </h3>
		<div id="event-arrow" style="display:none"></div>

	  <table class="table table-striped event-table">
	    <thead>
	      <tr>
	        <th>Classification</th>
	        <th></th>
	      </tr>
	    </thead>
	    <tbody>
				<tr>
					<td style="color:green">Action</td>
					<td><%= @event_data['action'] || '---' %></td>
				</tr>
				<tr>
					<td style="color:red">Domain</td>
					<td><%= @event_data['domain'] || '---' %></td>
				</tr>
				<tr>
					<td style="color:blue">Status</td>
					<td><%= @event_data['status'] || '---' %></td>
				</tr>
				<tr>
					<td style="color:orange">Object</td>
					<td><%= @event_data['object'] || '---' %></td>
				</tr>
				<tr>
					<td style="color:purple">Service</td>
					<td><%= @event_data['service'] || '---' %></td>
				</tr>
	    </tbody>
	  </table>
	</div>

	<div id="tags">
		<h3> Tags: </h3>
		<div id="tag-field">
			<% @pattern_source.tags.each do |tag| %>
        <div class="tag"><%= tag.text %></div>
      <% end %>
		</div>
	</div>

	<div id="source">
		<% text = ((@source != '' && @source) ? @source : 'not stated') %>
		Log is from source: <strong><%= text %></strong>
	</div>
<% else %>
	<h2> No log was processed yet, try to analyze some in log management first</h2>
<% end %>


</div>

app/views/events/taxonomy.html.erb
<p id="notice"><%= notice %></p>
<p id="warn" style="color:red"><%= warn %></p>

<div class="form-group activity" id="log-patterns">
  <%= form_tag("/taxonomy", method: "get") do %>
    <div id="search-input">
      <%= text_field_tag :search, params[:search], placeholder: 'search', class: "form-control left" %>
    </div>
    <%= submit_tag "Search", class: "btn btn-default left", id: "search-submit" %>
  <% end %>
</div>

<% if @events.present? %>

<div id="table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Tag</th>
        <th>Classification</th>
        <th>Description</th>
        <th>Synonyms</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <% #color = (event.original == true ? 'blue' : 'red') %>
        <tr>
          <td id="e-tag"><%= event.tag %></td>
          <%
          case event.clasification
          when 'action'
            color = 'green'
          when 'domain'
            color = 'red'
          when 'status'
            color = 'blue'
          when 'object'
            color = 'orange'
          when 'service'
            color = 'purple'
          else
            color = 'grey'
          end
          %>
          <td id="e-class" style="color:<%= color %>"><%= event.clasification %></td>
          <td id="e-desc"><%= event.description %></td>
          <td id="e-synonyms">
            <select class="form-control">
            <% event.synonyms.each do |synonym| %>
              <option><%= synonym.text %></option>
            <% end %> 
            </select>
          </td>
          <td id="add-synonym">
            <%= button_to edit_event_path(event), class: "btn btn-primary", :method => :get do %>
              Manage synonyms
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <p>There are no events containing the term(s) <%= params[:search] %>.</p>
<% end %>