config/routes.rb
Rails.application.routes.draw do
  resources :patterns
  resources :logs
  resources :users
  resources :parsers
  resources :events
  resources :synonyms
  
  root "sessions#new"

  get "sessions/new"
  get "users/new"

  get "/start" => "analyzer#index"
  get "/analyze" => "analyzer#analyze"
  get "analyzer/group"
  get "/split" => "analyzer#split_element"
  get "/save_text" => "analyzer#save_text"
  get "/replace" => "analyzer#replace_data"
  post "/save_log" => "analyzer#save_log"
  post "/save_log_success" => "analyzer#save_log_success"
  get "/search" => "analyzer#help_search"
  
  get "/event" => "events#index"
  get "/taxonomy" => "events#taxonomy"
  post "/save_synonym" => "events#save_synonym"
  post "/save_event" => "events#save_event"
  post "/save_tag" => "events#save_tag"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/signup" => "users#new"
  post "/users" => "users#create"
  get "/users" => "users#index"

  get "/parsers" => "parsers#index"
  get "/export_parsers" => "parsers#export"
  post "/form" => "parsers#form_save"
  post "/import_parsers" => "parsers#import"
  resources :parsers do
    get :autocomplete_parser_name, :on => :collection
  end

  get "/patterns" => "patterns#index"
  post "/save" => "patterns#create_with_log"
  get "patterns/autocomplete_pattern_text"
  get "/export_patterns" => "patterns#export"
  post "/import_patterns" => "patterns#import"

  get "/export_logs" => "logs#export"
  

end

app/models/parser.rb
class Parser < ActiveRecord::Base
	def self.search(search)
    if search
      where("LOWER(name) LIKE :search OR LOWER(expression) LIKE :search OR LOWER(source_group) LIKE :search", search: "%#{search.downcase}%") 
    else
      []
    end
  end 
end

app/controllers/parsers_controller.rb
class ParsersController < ApplicationController
	require 'grok-pure'
  require 'csv'
  require 'pp'
  respond_to :json, :html, :js
  add_flash_types :success, :warn
  autocomplete :parser, :name, :full => true

	def index
    @parser = Parser.new
		if params[:search]
      @parsers = Parser.search(params[:search]) 
    else
      @parsers = Parser.all
    end

    @tokens = []
    @groups = []

    @parsers.each do |item|
      if item[:expression].match(/%{.*}/)
        @groups << item
      else
        @tokens << item
      end
    end

    @groups.sort_by! {|item| item.name.downcase}
    @tokens.sort_by! {|item| item.name.downcase}
  end

  def show
  end

  # GET /parsers/new
  def new
    @parser = Parser.new
  end

  # GET /parsers/1/edit
  def edit
  	@parser = Parser.find(params[:id])
  end

  def form_save
    @parser = Parser.new(
                          name: params[:name],
                          expression: params[:expression],
                          blacklist: params[:blacklist],
                          source_group: params[:source_group]
                        )
    respond_to do |format|
      if @parser.save
        format.js # discover vzor a poslat do JS
        format.html { redirect_to '/parsers' , notice: 'Parser was successfully created.' }
        format.json { render :show, status: :created, location: @parser }
      else
        format.html { render :new }
        format.json { render json: @parser.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @parser = Parser.new(parser_params)

    respond_to do |format|
      if @parser.save
        format.html { redirect_to '/parsers', notice: 'Parser was successfully created.' }
        format.json { render :show, status: :created, location: @parser }
      else
        format.html { render :new }
        format.json { render json: @parser.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  	@parser = Parser.find(params[:id])
    patterns = Pattern.all
    pattern_names = []
    able = true
    name_changed = false

    patterns.each do |pattern|
      pattern_names << pattern.text
    end
    
    if parser_params[:name] != @parser.name
      name_changed = true
    end

    if name_changed
      pattern_names.each do |item|
        if item.include? '%{' + @parser.name.to_s + '}'
          able = false
        end
      end
    end

    respond_to do |format|
      if able
        if @parser.update(parser_params)
          format.html { redirect_to '/parsers', notice: 'Parser was successfully updated.' }
          format.json { render :show, status: :ok, location: @parser }
        else
          format.html { render :edit }
          format.json { render json: @parser.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to edit_parser_path(@parser), warn: "Can't update parser name because it is present in pattern(s)" }
      end
    end
  end

  def destroy
    @parser = Parser.find(params[:id])
    patterns = Pattern.all
    pattern_names = []
    able = true

    patterns.each do |pattern|
      pattern_names << pattern.text
    end

    pattern_names.each do |item|
      if item.include? '%{' + @parser.name.to_s + '}'
        able = false
      end
    end

    respond_to do |format|
      if able
        if @parser.present?
          @parser.destroy
        end
        format.html { redirect_to parsers_url, notice: 'Parser was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to parsers_url, warn: "Can't destroy parser because it is present in pattern(s)" }
      end
    end
  end

  def export
    parsers = []
    Parser.all.each do |parser|
      parsers << {
                   name: parser.name,
                   expression: parser.expression,
                   blacklist: parser.blacklist,
                   source_group: parser.source_group
                 }
    end
    data = JSON.pretty_generate(parsers)

    file = "parsers.json"
    File.open(file, "w"){ |f| f << data }
    send_file( file )
  end

  def import
    uploaded_file = params[:file]
    file_content = uploaded_file.read
    parsers = JSON.parse(file_content)

    parsers.each do |p|
      parser = Parser.new(
                          name: p['name'],
                          expression: p["expression"],
                          blacklist: p["blacklist"],
                          source_group: p["source_group"]
                          )
      next unless parser.save
    end

    redirect_to '/parsers'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def parser_params
      params.require(:parser).permit(:name, :expression, :blacklist, :source_group)
    end 
end

app/helpers/parsers_helper.rb
module ParsersHelper
end

app/views/parsers/_form.html.erb
<%= form_for(@parser) do |f| %>
	<div class="form-group">
		<%= label_tag(:name, "Name:") %>
	  <%= f.text_field :name, class: "form-control" %>
	  <%= label_tag(:expression, "Expression:") %>
	  <%= f.text_area :expression, class: "form-control" %>
	  <%= label_tag(:blacklist, "Blacklist:") %>
	  <%= f.check_box :blacklist, class: "form-control" %>
	  <%= label_tag(:source_group, "Source group:") %>
	  <%= f.text_field :source_group, class: "form-control" %>
	  <%= f.submit "Submit", class: "btn btn-default btn-lg", id: "add-pattern" %>
	</div>
<% end %>

app/views/parsers/_groups.html.erb
<% if @groups.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Expression</th>
      <th>Blacklist</th>
      <th>Source group</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |item| %>
      <tr>
        <td id="name"><%= item.name %></td>
        <td id="expression"><%= item.expression %></td>
        <td id="blacklist">
          <%= check_box_tag 'blacklisted', '1', item.blacklist, disabled: true %>
        </td>
        <td id="group"><%= item.source_group %></td>
        <td id="edit">
          <%= button_to edit_parser_path(item), class: "btn btn-success", :method => :get do %>
            Edit
          <% end %>
        </td>
        <td id="destroy">
          <%= button_to item, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>There are no groups containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/parsers/_parsers.html.erb
<% if data.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Expression</th>
      <th>Blacklist</th>
      <th>Source group</th>
      <% if current_user.role == 'admin' %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% data.each do |item| %>
      <tr>
        <td id="p-name"><%= item.name %></td>
        <td id="p-expression"><%= item.expression %></td>
        <td id="p-blacklist">
          <%= check_box_tag 'blacklisted', '1', item.blacklist, disabled: true %>
        </td>
        <td id="p-group"><%= item.source_group %></td>
        <% if current_user.role == 'admin' %>
          <td id="edit">
            <%= button_to edit_parser_path(item), class: "btn btn-success", :method => :get do %>
              Edit
            <% end %>
          </td>
          <td id="destroy">
            <%= button_to item, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
              Delete
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>There are no parsers containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/parsers/edit.html.erb
<div id="new-parser">
	<p id="warn" style="color: red;"><%= warn %></p>
	<h1>Editing Parser</h1>

	<%= render 'form' %>

	<%= button_to parsers_path, class: "btn btn-default btn-lg edit-parser", :method => :get do %>
	  Back
	<% end %>

</div>

app/views/parsers/form_save.js.erb
$('#approvalModal').modal('hide');

$('#notice').html('Parser was sucesfully created');

app/views/parsers/index.html.erb
<p id="notice"><%= notice %></p>
<p id="warn" style="color: red;"><%= warn %></p>

<div class="form-group activity" id="log-patterns">
  <select class="form-control parsers left" id="sel1">
    <option>Tokens</option>
    <option>Groups</option>
  </select>

  <%= button_to 'New parser', new_parser_path, class: "btn btn-primary left", :method => :get %>

	<%= form_tag("/parsers", method: "get") do %>
		<div id="search-input">
		  <%= text_field_tag :search, params[:search], placeholder: 'search', class: "form-control left" %>
		</div>
	  <%= submit_tag "Search", class: "btn btn-default left", id: "search-submit" %>
	<% end %>

	<%= button_to 'Export', '/export_parsers', class: "btn btn-primary right export", :method => :get %>

	<%= form_tag '/import_parsers', class: "import-parser right", :multipart => true do %>
   <%= file_field_tag :file, class: "btn btn-default left" %>
   <%= submit_tag 'Import file', class: "btn btn-primary left" %>
  <% end %>
</div>
 
<div class="table">
	<div id='tokens'>
		<%= render :partial => 'parsers', locals: { data: @tokens } %>
	</div>
	<div id='groups' style='display:none'>
	  <%= render :partial => 'parsers', locals: { data: @groups } %>
	</div>
</div>

app/views/parsers/new.html.erb
<div id="new-parser">

<h1> New parser </h1>

<%= render 'form' %>

<%= button_to parsers_path, class: "btn btn-default btn-lg edit-parser", :method => :get do %>
  Back
<% end %>

</div>

app/views/parsers/show.html.erb
<p id="notice"><%= notice %></p>