config/routes.rb
Rails.application.routes.draw do
  resources :patterns
  resources :logs
  resources :users
  resources :parsers
  resources :events
  resources :synonyms
  
  root "sessions#new"

  get "sessions/new"
  get "users/new"

  get "/start" => "analyzer#index"
  get "/analyze" => "analyzer#analyze"
  get "analyzer/group"
  get "/split" => "analyzer#split_element"
  get "/save_text" => "analyzer#save_text"
  get "/replace" => "analyzer#replace_data"
  post "/save_log" => "analyzer#save_log"
  post "/save_log_success" => "analyzer#save_log_success"
  get "/search" => "analyzer#help_search"
  
  get "/event" => "events#index"
  get "/taxonomy" => "events#taxonomy"
  post "/save_synonym" => "events#save_synonym"
  post "/save_event" => "events#save_event"
  post "/save_tag" => "events#save_tag"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/signup" => "users#new"
  post "/users" => "users#create"
  get "/users" => "users#index"

  get "/parsers" => "parsers#index"
  get "/export_parsers" => "parsers#export"
  post "/form" => "parsers#form_save"
  post "/import_parsers" => "parsers#import"
  resources :parsers do
    get :autocomplete_parser_name, :on => :collection
  end

  get "/patterns" => "patterns#index"
  post "/save" => "patterns#create_with_log"
  get "patterns/autocomplete_pattern_text"
  get "/export_patterns" => "patterns#export"
  post "/import_patterns" => "patterns#import"

  get "/export_logs" => "logs#export"
  

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
	has_many :logs, dependent: :destroy
	has_many :tags, dependent: :destroy
	validates :text, :uniqueness => true

	def self.search(search)
    if search
      where("LOWER(text) LIKE :search", search: "%#{search.downcase}%") 
    else
      []
    end
  end 

end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]
  autocomplete :pattern, :text, :full => true
  require 'pp'
  # GET /patterns
  # GET /patterns.json
  def index
    if params[:search]
      @patterns = Pattern.search(params[:search]).order(created_at: :desc)
    else
      @patterns = Pattern.all.order(created_at: :desc)
    end
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)
    parsers = Parser.all
    parser_names = []
    parts = @pattern[:text].split(/[\s|\/]/)
    @recognized = true
    @unknown = ''

    parsers.each do |parser|
      parser_names << parser.name
    end

    parts.each do |part|
      unless parser_names.include? part.gsub(/[\{\}\%]/, '')
        @unknown = part
        @recognized = false
      end
    end

    respond_to do |format|
      if @uknown == ''
        if @pattern.save
          format.html { redirect_to '/patterns', notice: 'Pattern was successfully created.' }
          format.json { render :show, status: :created, location: @pattern }
        else
          format.html { redirect_to '/patterns/new', notice: 'Pattern is already present in the database.' }
          format.json { render json: @pattern.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to '/patterns/new', notice: 'Unknown parser for '+ @unknown }
      end
    end
  end

  def export
    patterns = []
    Pattern.all.each do |pattern|
      patterns << {
                    pattern: pattern.text,
                    source: pattern.source,
                    event_pattern: pattern.event_pattern
                  }
    end
    data = JSON.pretty_generate(patterns)

    file = "patterns.json"
    File.open(file, "w"){ |f| f << data }
    send_file( file )
  end

  def import
    uploaded_file = params[:file]
    file_content = uploaded_file.read
    patterns = JSON.parse(file_content)

    patterns.each do |p|
      pattern = Pattern.new(
                            text: p['pattern'],
                            source: p["source"],
                            event_pattern: p["event_pattern"]
                            )
      next unless pattern.save
    end

    redirect_to '/patterns'
  end

  def create_with_log
    @pattern = Pattern.new(pattern_params)
    parsers = Parser.all
    parser_names = []
    parts = @pattern[:text].split(/[\s|\/]/)
    @recognized = true
    @unknown = ''

    parsers.each do |parser|
      parser_names << parser.name
    end
    
    parts.each do |part|
      unless parser_names.include? part.gsub(/[\{\}\%]/, '')
        @unknown = part
        @recognized = false
      end
    end

    respond_to do |format|
      if @recognized
        if @pattern.save
          log = Log.new(text: params[:log], pattern_id: @pattern.id)
          log.save
          format.html { redirect_to '/patterns', notice: 'Pattern was successfully created.' }
          format.json { render :show, status: :created, location: @pattern }
        else
          format.js
          format.html { render :new }
          format.json { render json: @pattern.errors, status: :unprocessable_entity }
        end
      else
        format.js
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to '/patterns', notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:text, :source)
    end
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/patterns/_form.html.erb
<%= form_for @pattern do |f| %>
	<div class="form-group">
		<%= label_tag(:text, "Pattern:") %>
    <%= f.text_area :text, class: "form-control stretch"%>
    <%= label_tag(:source, "Source:") %>
	  <%= f.text_field :source, class: "form-control" %>
    <%= f.submit "Submit", class: "btn btn-default btn-lg", id: "pattern-create" %>
  </div>
<% end %>

app/views/patterns/create_with_log.js.erb
var recognized = <%= @recognized %>;
if (recognized) {
	$('#warn').html("Pattern is already present in the database");
} else {
	$('#warn').html("Unrecognized parser for: <%= @unknown %>");
}

window.scrollTo(0, 0);

app/views/patterns/edit.html.erb
<div id="new-pattern">
  <h1>Editing Pattern</h1>

  <%= render 'form' %>

  <%= button_to patterns_path, class: "btn btn-default btn-lg edit-pattern", :method => :get do %>
    Back
  <% end %>
</div>

<div id="pattern-samples">

  <div id="table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th> Corresponding event data: </th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <% data = (@pattern.try(:event_pattern) ? @pattern.event_pattern : '') %>
            <% data.gsub!(/ /, ' - ') %>
            <td id="event"><strong> <%= (data != '' ? data : 'no event data') %> </strong></td>
          </tr>
      </tbody>
    </table>
  </div>

  <div id="divider"></div>

    <div id="edit-tag">
      <strong>TAGS:</strong>
      <% @pattern.tags.each do |tag| %>
        <div class="tag"><%= tag.text %></div>
      <% end %>
    </div>

  <div id="divider"></div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th> Log samples: </th>
      </tr>
    </thead>
    <tbody>
      <% @pattern.logs.each do |log| %>
        <tr>
          <td><%= log.text %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/patterns/index.html.erb
<div class="options">
  <%= button_to 'New Pattern', new_pattern_path, class: "btn btn-primary left", :method => :get %>

  <%= form_tag("/patterns", method: "get") do %>
    <div id="search-input">
      <%= text_field_tag :search, params[:search], placeholder: 'search', class: "form-control left" %>
    </div>
    <%= submit_tag "Search", class: "btn btn-default left", id: "search-submit" %>
  <% end %>

  <%= button_to 'Export', '/export_patterns', class: "btn btn-primary right export", :method => :get %>
  

  <%= form_tag '/import_patterns', class: "import right", :multipart => true do %>
   <%= file_field_tag :file, class: "btn btn-default left" %>
   <%= submit_tag 'Import file', class: "btn btn-primary left" %>
  <% end %>
</div>

<p id="notice"><%= notice %></p>

<% if @patterns.present? %>
<div id="table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Pattern</th>
        <th>Source</th>
        <th>Log samples</th>
        <% if current_user.role == 'admin' %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @patterns.each do |pattern| %>
        <tr>
          <td id="pat-text"><%= pattern.text %></span></td>
          <td id="pat-source"><%= pattern.source %></span></td>
          <td id="pat-logs">
            <select class="form-control">
            <% pattern.logs.limit(5).each do |log| %>
              <option><%= log.text %></option>
            <% end %> 
            </select>
          </td>
          <% if current_user.role == 'admin' %>
            <td id="edit">
              <%= button_to edit_pattern_path(pattern), class: "btn btn-success", :method => :get do %>
                Edit
              <% end %>
            </td>
            <td id="destroy">
              <%= button_to pattern, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
                Delete
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <p>There are no patterns containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/patterns/new.html.erb
<div id="new-pattern">
	<p id="notice" style="color: red;"><%= notice %></p>

	<h1>New Pattern</h1>

	<%= render 'form' %>

	<%= button_to patterns_path, class: "btn btn-default btn-lg edit-pattern", :method => :get do %>
	  Back
	<% end %>
</div>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @pattern.text %></strong>
</p>